### ISSUE TITLE
关于女，驴，绿，旅等发音为“lv”、“nv”无法切分的情况

### ISSUE THREAD

**Issue by Vange95** [shibing624/pinyin-tokenizer#1]
当我输入lvyou(旅游)，nvren(女人)等拼音时，算法会将lv，nv等内容过滤掉，只剩下其余的部分，导致切分失败

**Comment by Vange95** [comment]
把pinyintokenizer文件夹下的__init__.py文件中的self.add(["l", "u:e"])改成self.add(["l", "v"])，self.add(["n", "u:e"])改成self.add(["l", "v"])即可，此外我还添加了self.add(["l", "ve"])和self.add(["n", "ve"])用以识别略，掠，虐，疟等字的拼音

**Comment by shibing624** [comment]
感谢，我加下。

**Comment by Vange95** [comment]
首先要感谢您开发的pinyintokenizer，哈哈，很好用👍
向您学习！

发件人: Ming Xu (徐明) ***@***.***>
日期: 星期四, 2023年6月8日 15:35
收件人: shibing624/pinyin-tokenizer ***@***.***>
抄送: Vange95 ***@***.***>, State change ***@***.***>
主题: Re: [shibing624/pinyin-tokenizer] 关于女，驴，绿，旅等发音为“lv”、“nv”无法切分的情况 (Issue #1)

感谢，我加下。
